name: foodapi
description: Food API
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: 3.2.9
  jaguar_jwt: 3.0.0
  # uuid:

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.0.0
