name: foodapi
description: Food API
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^4.4.0
  uuid: any

dev_dependencies:
  test: ^1.22.1
  conduit_test: ^4.0.0
